steps:
  # 1) Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gas-bot'
      - '.'
    id: Build

  # 2) Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gas-bot'
    id: Push

  # 3) Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gas-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gas-bot'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: Deploy

timeout: '1200s'
images:
  - 'gcr.io/$PROJECT_ID/gas-bot'
